deepspeed --include localhost:1 --master_port=24999 train_SIDA.py \
  --version="./ck/LISA-7B-v1" \
  --dataset_dir='/mnt/traffic/home/dingkuiye/SID_Set' \
  --vision_pretrained="/mnt/traffic/home/dingkuiye/sam_vit_h_4b8939.pth" \
  --val_dataset="/mnt/traffic/home/dingkuiye/SID_Set/"\
  --batch_size=2 \
  --exp_name="SIDA-7B" \
  --epochs=5 \
  --steps_per_epoch=100 \
  --lr=0.0001 \
